=== kod-kristoff/karp-backend/src/karp/schema/resourceconf.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://spraakbanken.gu.se/resourceconf.schema.json",
  "title": "Resource configuration",
  "description": "",
  "type": "object",
  "properties": {
    "resource_id": {
      "description": "The unique identifier for a resource",
      "type": "string"
    },
    "resource_name": {
      "description": "The name of the resource",
      "type": "string"
    },
    "fields": {
      "description": "The fields of the resource",
      "type": "object",
      "patternProperties": {
        "^.*$":  {
          "oneOf": [
            { "$ref": "#/types/object" },
            { "$ref": "#/types/elem" }
          ]
        }
      }
    },
    "sort": {
      "description": "Default sorting order for the resource",
      "type": "string"
    },
    "protected": {
      "description": "Settings for the permissions of the corpora",
      "type": "object",
      "properties": {
        "write": {
          "type": "string"
        },
        "read": {
          "type": "string"
        }
      }
    },
    "id": {
      "type": "string"
    }
  },
  "required": ["resource_id", "resource_name", "fields", "sort"],
  "types": {
    "object": {
      "oneOf": [
        { "$ref": "#/types/another_object" },
        { "$ref": "#/types/elem" }
      ]
    },
    "another_object": {
      "type": "object"
    },
    "elem": {
      "type": "string"
    }
  }
}

=== kod-kristoff/karp-backend/tests/data/config/places.json
{
  "resource_id": "places",
  "resource_name": "Platser i Sverige",
  "fields": {
    "name": {
      "type": "string",
      "required": true
    },
    "municipality": {
      "type": "string",
      "required": true
    },
    "population": {
      "type": "number"
    },
    "area": {
      "type": "number"
    },
    "density": {
      "type": "number"
    },
    "code": {
      "type": "number",
      "required": true
    }
  },
  "sort": "name",
  "id": "code"
}

=== kod-kristoff/karp-backend/assets/testing/config/places.json
{
  "resource_id": "places",
  "resource_name": "Platser i Sverige",
  "fields": {
    "name": {
      "type": "string",
      "required": true
    },
    "municipality": {
      "collection": true,
      "type": "integer",
      "required": true
    },
    "larger_place": {
      "type": "integer"
    },
    "population": {
      "type": "integer"
    },
    "area": {
      "type": "integer"
    },
    "density": {
      "type": "integer"
    },
    "code": {
      "type": "integer",
      "required": true
    }
  },
  "sort": "name",
  "id": "code"
}
